# Generated by Django 4.2.2 on 2023-09-25 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='name',
            new_name='branchname',
        ),
        migrations.RenameField(
            model_name='district',
            old_name='name',
            new_name='districtname',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='District',
        ),
    ]
